### ISSUE TITLE
About neural field editing experiment.

### ISSUE THREAD

**Issue by MinJunKang** [hbb1/PREF#3]
Hello, thanks for sharing the nice and interesting work!

Since your feature encoder (PREF) is based on Fourier Transform, I guess that we can continuously express the multiple scales of the signal by changing the frequency bandwidth of the encoding volume or input signal. My questions are:

1. What is the clear difference between modifying linear_freqs and reduced_freqs of PREF and applying the gaussian kernel to input coordinates (mentioned in Figure 6. of the manuscript and also explained in Sec E of supplementary material)?
2. Can we apply both techniques in the training stage for progressive learning (coarse to fine)? Is this beneficial for PREF to express multi-scale signals without aliasing effect as BACON did (similar to Fig.4 of BACON's manuscript)?
3. What is the role of alpha of PREF?

Sorry for asking a lot of questions. I am looking for the possibility of whether this work is the voxel-based nerf that can continuously encode signals of multi-scales (For example, by varying sigma in Gaussian Filter). I am also curious about your personal opinion regarding this.

Thanks a lot!

**Comment by hbb1** [comment]
Hi, thanks for your interest.  Here I share some of my experiences.
1. The difference is only related to their frequency coordinates: high frequencies are cut down. The design of so-called dilated phasor volume (linear_freqs and reduced_freqs) is for compact purposes.  But you can thank the dilated phasor volume as a full volume (the dual of spatial volume) with many entries being zeros.  So there is no special difference between the linear_freqs and reduced_freqs.
2. Actually this is what we did in our early experiments! In the training phase, we multiply the volume with such a kernel with a large variance at the beginning and gradually decrease the variance.  It has a similar effect to our regularization term. Whereas how to decay the variance can be tricky, we find the regularization term is more convenient. 
4. Similar to BACON, the output of our encoder can also be expressed as a summation of sines so that it should achieve similar effects. For image regression, you may supervise the grid at multiple bandwidths as BACON did. Functions used in the progressive training can be useful.  
5. Alpha is to stable the training of phasor volume. We find that our representation cannot converge well without this term. 

These are somewhat based on my personal experiences and assumptions. I planned to add additional experiments with multi-scale supervision to verify this.

**Comment by MinJunKang** [comment]
Thanks for your precious comments! Your comments helped me a lot.

**Comment by MinJunKang** [comment]
![image](https://user-images.githubusercontent.com/29685163/189146588-aea6b7f4-cfe1-42fb-b792-9bf9a28f5482.png)
With your comment, I could reproduce your shape editing result with hotdog scene. Thanks a lot!

**Comment by hbb1** [comment]
Hi, thank you for pointing out this. BTW, I see some outliers though, adjusting view direction's bandwidth accordingly may further improve the results, since the radiance field is a 5D representation (the additional 2D view direction is not modelled with the 3D phasor volume). A very small comment: I suggest not using 2D viewdir as input at first to examine the multi-scale representation just as BACON did.

**Comment by MinJunKang** [comment]
Thanks for your helpful comment. Since removing view direction degrades the performance a lot, I try using Spherical Harmonics to encode view direction instead of positional encoding. This not only improves the overall performance (hotdog PSNR : 36.2 -> 36.4) but also removes the positional encoding part that can affect bandwidth. In this way, maybe we can control scale of the output purely based on the variance of gaussian kernel.

**Comment by MinJunKang** [comment]
Thanks for your constructive comment. Now, I will close this issue!
